services:
  #new service (java_app)
  java_crud_app:
    container_name: java_crud_app
    image: java_crud_app_image
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres_db:5432/users
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - postgres_db


  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: {}
    
