services:
  postgres:
    container_name: 'postgres_db'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=users'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
    
